### ISSUE TITLE
Add support for Windows for more converters

### ISSUE THREAD

**Issue by ravensorb** [agilebits/onepassword-utilities#24]
Considering the number of Windows PCs on the market -- I am really impressed how few of the importers are supported/tested on windows.  Please consider adding support for more of them on windows (especially CSV)

**Comment by mikecappella** [comment]
Hi there.  I'm not sure I understand exactly what you're referring to.  If you are talking about the convert_to_1p4 converter, your claim doesn't make sense to me, since almost all of the converters for which there is a Windows version of the given password manager, work on and have been tested on Windows.   More specifically, the csv converter works on both Windows and OS X.

Please follow up, or ask any additional questions, or post your comments / requests here:

https://discussions.agilebits.com/discussion/30286/mrcs-convert-to-1password-utility/p1

As I'd like to keep all discussion on the converters in an area readily found by 1Password users.
